#!/bin/bash
set -e
cd "$(dirname "$0")/.."

file=".travis.d/credential.json"
if [ -z "${encryption_key}" -o \
     -z "${encryption_iv}" -o \
     ! -f "${file}.enc" ]; then
  exit 0
fi

if [ -f "${file}" ]; then
  openssl \
      aes-256-cbc -d \
      -K "${encryption_key}" -iv "${encryption_iv}" \
      -in "${file}.enc" -out "${file}.tmp"
  cmp "${file}.tmp" "${file}"
  rv="$?"
  rm "${file}.tmp"
  exit "${rv}"
fi

openssl \
    aes-256-cbc -d \
    -K "${encryption_key}" -iv "${encryption_iv}" \
    -in "${file}.enc" -out "${file}"
