#!/bin/bash
set -e
cd "$(dirname "$0")/.."

encryption_key="$(od -w32 -An -x -N32 /dev/urandom | sed 's/ //g')"
encryption_iv="$(od -w16 -An -x -N16 /dev/urandom | sed 's/ //g')"

echo "encryption_key=${encryption_key}"
echo "encryption_iv=${encryption_iv}"

file=".travis.d/credential.json"
openssl \
    aes-256-cbc -e \
    -K "${encryption_key}" -iv "${encryption_iv}" \
    -in "${file}" -out "${file}.enc"
