language: go

go:
  - 1.8.x

before_install:
  - bin/decrypt
  - bin/install_gcp_sdk
  - source "${HOME}/google-cloud-sdk/path.bash.inc"

cache:
  directories:
    - "${HOME}/google-cloud-sdk"

deploy:
  provider: gae
  project: "tzik-jp"
  keyfile: "etc/secret/deploy_key.json"
  config: "gae/app.yaml"
  on: "staging"
  version: "staging"
  no_promote: true
  no_stop_previous_version: true
