language: go

go:
  - 1.8.x

before_install:
  - bin/decrypt

deploy:
  provider: gae
  project: "tzik-jp"
  keyfile: "etc/secret/deploy_key.json"
  on: staging
  no_promote: true
  no_stop_previous_version: true
